networks:
  chatakon-network:
    driver: bridge
services:
  chatakon-agentic:
    build:
      context: "./services/agentic"
    container_name: "chatakon-agentic"
    env_file:
      - ./.env
    command: ["fastapi", "run", "./app/Agentic.py", "--port", "8001"]
    networks:
      - chatakon-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 10s
      timeout: 2s
      retries: 5
  chatakon-front:
    build:
      context: "./front"
    container_name: "chatakon-front"
    ports:
      - "8091:3000"
      - "8010:8000"
    environment:
      - REFLEX_API_URL=https://chatakon.fr
    depends_on:
      - chatakon-agentic
    networks:
     - chatakon-network
    command: ["reflex", "run", "--env", "prod"]
